### ISSUE TITLE
Review schedule

### ISSUE THREAD

**Issue by jrnold** [UW-POLS501/2018#3]
The content of the schedule is in `content/schedule/_index.md`. Almost all of it is in the YAML header.  It relies upon `themes/pols501/layouts/schedule/list.html` to render it.

**Comment by calvinhgarner** [comment]
- For Week 2, there is no link to Simpson's Paradox - notes
- For Week 4, there is no link to Description, EDA, and Measurement Notes
- For Week 5, there is no link to Prediction or Cross Validation Notes

Also, it seems like schedule is only set through Week 6.

**Comment by jrnold** [comment]
I'm confused by what you mean by schedule set through week 6. All weeks are appearing in  https://uw-pols501.github.io/2018/schedule/.
