### ISSUE TITLE
Link error?

### ISSUE THREAD

**Issue by kenyamano** [UW-POLS501/2018#37]
At the schedule of the class website, QSS on week 1 reading list has a link, but is this link R4DS?

https://uw-pols501.github.io/2018/schedule/
Week 1
Friday, Jan 5, 2018 Class
Readings before:

QSS Ch 1. “Introduction“ 
<- Does this need link? it seems jumping into R4DS.

**Comment by jrnold** [comment]
Thanks! Fixed.
